### ISSUE TITLE
BUG: API 20141201: Schedule returns stationID as integer

### ISSUE THREAD

**Issue by Slugger** [SchedulesDirect/JSON-Service#53]
For my download of a few hundred channels, just one schedule actually produced this error, but none the less it did.  According to spec, the stationID fields should be a string, not a number and every other schedule I received followed the rule.

```
*** S T A C K  T R A C E ***
org.schedulesdirect.api.exception.InvalidJsonObjectException: Error with schedule: JSONObject["stationID"] not a string.
	at org.schedulesdirect.grabber.ScheduleTask.fetchStations(ScheduleTask.java:140)
	at org.schedulesdirect.grabber.ScheduleTask.run(ScheduleTask.java:87)
	at java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at org.schedulesdirect.grabber.Grabber.updateZip(Grabber.java:548)
	at org.schedulesdirect.grabber.Grabber.execute(Grabber.java:817)
	at org.schedulesdirect.grabber.Grabber.main(Grabber.java:924)
Caused by: org.json.JSONException: JSONObject["stationID"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at org.schedulesdirect.grabber.ScheduleTask.fetchStations(ScheduleTask.java:133)
	... 7 more

*** I N P U T ***
{
   "programs": [
      {
         "programID": "SH020837050000",
         "duration": 1800,
         "airDateTime": "2015-03-30T01:00:00Z",
         "md5": "HUNa2dqCBY5ZA3f5U8FNEw"
      },
      {
         "programID": "SH020837050000",
         "duration": 1800,
         "airDateTime": "2015-03-30T01:30:00Z",
         "md5": "HUNa2dqCBY5ZA3f5U8FNEw"
      },
      {
         "programID": "SH001047280000",
         "duration": 7200,
         "airDateTime": "2015-03-30T02:00:00Z",
         "md5": "bqkM2t7CZ3X3Fhu7gsf1Eg"
      },
      {
         "programID": "SH018945700000",
         "duration": 3600,
         "airDateTime": "2015-03-30T04:00:00Z",
         "md5": "eF8c6vRCwaP/t5rs2VUPEA",
         "repeat": true
      },
      {
         "programID": "SH016030850000",
         "duration": 1800,
         "airDateTime": "2015-03-30T05:00:00Z",
         "md5": "hECRxazbIL1Ij09g8ot9Tg",
         "repeat": true
      },
      {
         "programID": "SH016030850000",
         "duration": 1800,
         "airDateTime": "2015-03-30T05:30:00Z",
         "md5": "hECRxazbIL1Ij09g8ot9Tg",
         "repeat": true
      },
      {
         "programID": "SH016030850000",
         "duration": 1800,
         "airDateTime": "2015-03-30T06:00:00Z",
         "md5": "hECRxazbIL1Ij09g8ot9Tg",
         "repeat": true
      },
      {
         "programID": "SH000000010000",
         "duration": 1800,
         "airDateTime": "2015-03-30T06:30:00Z",
         "md5": "kOSFidqsgvjSMwIDFPirnA"
      },
      {
         "programID": "SH000000010000",
         "duration": 1800,
         "airDateTime": "2015-03-30T07:00:00Z",
         "md5": "kOSFidqsgvjSMwIDFPirnA"
      },
      {
         "programID": "SH000000010000",
         "duration": 1800,
         "airDateTime": "2015-03-30T07:30:00Z",
         "md5": "kOSFidqsgvjSMwIDFPirnA"
      },
      {
         "programID": "SH000000010000",
         "duration": 1800,
         "airDateTime": "2015-03-30T08:00:00Z",
         "md5": "kOSFidqsgvjSMwIDFPirnA"
      },
      {
         "programID": "SH000000010000",
         "duration": 1800,
         "airDateTime": "2015-03-30T08:30:00Z",
         "md5": "kOSFidqsgvjSMwIDFPirnA"
      },
      {
         "programID": "SH000000010000",
         "duration": 1800,
         "airDateTime": "2015-03-30T09:00:00Z",
         "md5": "kOSFidqsgvjSMwIDFPirnA"
      },
      {
         "programID": "SH000000010000",
         "duration": 1800,
         "airDateTime": "2015-03-30T09:30:00Z",
         "md5": "kOSFidqsgvjSMwIDFPirnA"
      },
      {
         "programID": "SH020837050000",
         "duration": 1800,
         "airDateTime": "2015-03-30T10:00:00Z",
         "md5": "HUNa2dqCBY5ZA3f5U8FNEw"
      },
      {
         "programID": "SH020837050000",
         "duration": 1800,
         "airDateTime": "2015-03-30T10:30:00Z",
         "md5": "HUNa2dqCBY5ZA3f5U8FNEw"
      },
      {
         "programID": "SH020837050000",
         "duration": 1800,
         "airDateTime": "2015-03-30T11:00:00Z",
         "md5": "HUNa2dqCBY5ZA3f5U8FNEw"
      },
      {
         "programID": "SH020837050000",
         "duration": 1800,
         "airDateTime": "2015-03-30T11:30:00Z",
         "md5": "HUNa2dqCBY5ZA3f5U8FNEw"
      },
      {
         "programID": "SH000354340000",
         "duration": 7200,
         "airDateTime": "2015-03-30T12:00:00Z",
         "md5": "/qE9OgR3aV2ngwWuVpHA5w"
      },
      {
         "programID": "SH001599740000",
         "duration": 7200,
         "airDateTime": "2015-03-30T14:00:00Z",
         "md5": "uaxwVnmEJp9iTsU7wF510Q"
      },
      {
         "programID": "SH016030850000",
         "duration": 1800,
         "airDateTime": "2015-03-30T16:00:00Z",
         "md5": "hECRxazbIL1Ij09g8ot9Tg",
         "repeat": true
      },
      {
         "programID": "SH016030850000",
         "duration": 1500,
         "airDateTime": "2015-03-30T16:30:00Z",
         "md5": "hECRxazbIL1Ij09g8ot9Tg",
         "repeat": true
      },
      {
         "programID": "SH001599740000",
         "duration": 7200,
         "airDateTime": "2015-03-30T16:55:00Z",
         "md5": "uaxwVnmEJp9iTsU7wF510Q"
      },
      {
         "programID": "SH001599740000",
         "duration": 7500,
         "airDateTime": "2015-03-30T18:55:00Z",
         "md5": "uaxwVnmEJp9iTsU7wF510Q"
      },
      {
         "programID": "SH017895040000",
         "new": true,
         "duration": 3600,
         "airDateTime": "2015-03-30T21:00:00Z",
         "md5": "ZXPowfg0jPMW9uD3+PWKxw"
      },
      {
         "programID": "SH016667330000",
         "new": true,
         "duration": 3600,
         "airDateTime": "2015-03-30T22:00:00Z",
         "md5": "+hkPQHFSS8zMcpjFM1vI5Q"
      },
      {
         "programID": "SH019931390000",
         "new": true,
         "duration": 7200,
         "airDateTime": "2015-03-30T23:00:00Z",
         "md5": "bzYlWrNslvx4mxaRv1sYvg"
      }
   ],
   "stationID": 91308,
   "metadata": {
      "startDate": "2015-03-30",
      "md5": "m4A9/pEdXOnDgxArJQOWKQ",
      "modified": "2015-03-12T19:05:57Z"
   }
}
```

**Comment by Slugger** [comment]
Note to self: Verify fix at ScheduleTask.java:133

**Comment by rkulagowski** [comment]
Fixed. Please confirm.

**Comment by Slugger** [comment]
Confirmed.
